// src/jobs/autoGenerateCutoffPeriodsJob.js
//
// Runs nightly at 2:00 AM. For each active DepartmentCutoffSettings, checks how
// many open future cutoff periods exist. If fewer than MIN_UPCOMING_PERIODS, generates
// the next GENERATE_MONTHS_AHEAD months. Deduplicates against existing periods.
//
// createdBy is set to the company's first admin user — this is a system action
// taken on behalf of the company, and the field is non-nullable in the schema.

const { prisma }              = require("@config/connection");
const { generatePeriodDates } = require("@services/Cutoff/cutoffGenerationService");

const MIN_UPCOMING_PERIODS  = 2;
const GENERATE_MONTHS_AHEAD = 3;

async function autoGenerateCutoffPeriodsJob() {
  console.log("\n📅 [AUTO CUTOFF GEN] Running...");

  const today = new Date();
  today.setHours(0, 0, 0, 0);

  const allSettings = await prisma.departmentCutoffSettings.findMany({
    where:   { isActive: true },
    include: { department: { select: { name: true } } },
  });

  if (allSettings.length === 0) {
    console.log("[AUTO CUTOFF GEN] No active department settings found — skipping.");
    return;
  }

  // Batch-fetch one admin per company to satisfy the non-nullable createdBy relation.
  const companyIds = [...new Set(allSettings.map((s) => s.companyId))];
  const admins = await prisma.user.findMany({
    where:  { companyId: { in: companyIds }, role: { in: ["admin", "superadmin"] } },
    select: { id: true, companyId: true },
    distinct: ["companyId"],
  });
  const adminByCompany = Object.fromEntries(admins.map((a) => [a.companyId, a.id]));

  let totalCreated = 0;
  let totalSkipped = 0;

  for (const settings of allSettings) {
    try {
      const adminId = adminByCompany[settings.companyId];
      if (!adminId) {
        console.warn(`[AUTO CUTOFF GEN] ⚠️  No admin found for company ${settings.companyId} — skipping ${settings.department.name}`);
        continue;
      }

      // Count open periods that haven't ended yet.
      const upcomingCount = await prisma.cutoffPeriod.count({
        where: {
          companyId:    settings.companyId,
          departmentId: settings.departmentId,
          periodEnd:    { gte: today },
          status:       "open",
        },
      });

      if (upcomingCount >= MIN_UPCOMING_PERIODS) {
        totalSkipped++;
        continue;
      }

      // generatePeriodDates is a pure function — no DB, safe to call directly.
      const periods = generatePeriodDates(
        settings.startDate,
        settings.frequency,
        settings.paymentOffsetDays,
        GENERATE_MONTHS_AHEAD,
        false  // future only — never backfill from a cron job
      );

      if (periods.length === 0) {
        totalSkipped++;
        continue;
      }

      // Dedup: skip any periodStart that already exists for this department.
      const existing = await prisma.cutoffPeriod.findMany({
        where: {
          companyId:    settings.companyId,
          departmentId: settings.departmentId,
          periodStart:  { in: periods.map((p) => new Date(p.periodStart)) },
        },
        select: { periodStart: true },
      });

      const existingStarts = new Set(
        existing.map((p) => p.periodStart.toISOString().slice(0, 10))
      );

      const newPeriods = periods.filter(
        (p) => !existingStarts.has(new Date(p.periodStart).toISOString().slice(0, 10))
      );

      if (newPeriods.length === 0) {
        totalSkipped++;
        continue;
      }

      await prisma.cutoffPeriod.createMany({
        data: newPeriods.map((period) => ({
          companyId:       settings.companyId,
          departmentId:    settings.departmentId,
          periodStart:     new Date(period.periodStart),
          periodEnd:       new Date(period.periodEnd),
          paymentDate:     new Date(period.paymentDate),
          frequency:       settings.frequency,
          status:          "open",
          isAutoGenerated: true,
          createdBy:       adminId,
        })),
      });

      totalCreated += newPeriods.length;
      console.log(`[AUTO CUTOFF GEN] ✅ ${settings.department.name}: +${newPeriods.length} period(s)`);
    } catch (err) {
      console.error(`[AUTO CUTOFF GEN] ❌ ${settings.department.name}:`, err.message);
    }
  }

  console.log(`[AUTO CUTOFF GEN] Done — ${totalCreated} created, ${totalSkipped} departments already covered.`);
}

module.exports = autoGenerateCutoffPeriodsJob;
