// src/jobs/autoGenerateCutoffPeriodsJob.js
//
// Runs nightly at 2:00 AM. For each active DepartmentCutoffSettings:
//   1. Find the latest existing period by periodEnd.
//   2. If a period starting on latestPeriodEnd + 1 already exists → skip.
//   3. If latestPeriodEnd is within LOOKAHEAD_DAYS of today → create exactly one
//      next period, carrying the span from the previous period (Option A).
//
// createdBy is set to the company's first admin user — this is a system action
// taken on behalf of the company, and the field is non-nullable in the schema.

const { prisma } = require("@config/connection");

// Generate the next period this many days before the current one ends.
const LOOKAHEAD_DAYS = 3;

async function autoGenerateCutoffPeriodsJob() {
  console.log("\n📅 [AUTO CUTOFF GEN] Running...");

  const today = new Date();
  today.setHours(0, 0, 0, 0);

  const lookaheadDate = new Date(today);
  lookaheadDate.setDate(lookaheadDate.getDate() + LOOKAHEAD_DAYS);

  const allSettings = await prisma.departmentCutoffSettings.findMany({
    where:   { isActive: true },
    include: { department: { select: { name: true } } },
  });

  if (allSettings.length === 0) {
    console.log("[AUTO CUTOFF GEN] No active department settings found — skipping.");
    return;
  }

  // Batch-fetch one admin per company to satisfy the non-nullable createdBy relation.
  const companyIds = [...new Set(allSettings.map((s) => s.companyId))];
  const admins = await prisma.user.findMany({
    where:    { companyId: { in: companyIds }, role: { in: ["admin", "superadmin"] } },
    select:   { id: true, companyId: true },
    distinct: ["companyId"],
  });
  const adminByCompany = Object.fromEntries(admins.map((a) => [a.companyId, a.id]));

  let totalCreated = 0;
  let totalSkipped = 0;

  for (const settings of allSettings) {
    try {
      const deptLabel = settings.department?.name ?? "No Department";
      const adminId   = adminByCompany[settings.companyId];

      if (!adminId) {
        console.warn(`[AUTO CUTOFF GEN] ⚠️  No admin for company ${settings.companyId} — skipping ${deptLabel}`);
        continue;
      }

      // 1. Find the latest period for this department.
      const latest = await prisma.cutoffPeriod.findFirst({
        where:   { companyId: settings.companyId, departmentId: settings.departmentId },
        orderBy: { periodEnd: "desc" },
      });

      if (!latest) {
        console.log(`[AUTO CUTOFF GEN] ⏭  ${deptLabel}: no existing periods — skipping.`);
        totalSkipped++;
        continue;
      }

      // 2. Check if the next period already exists.
      // Use UTC methods — periodEnd is stored as UTC midnight, and local-time
      // date arithmetic (getDate/setDate) shifts the day in non-UTC timezones.
      const nextStart = new Date(latest.periodEnd);
      nextStart.setUTCDate(nextStart.getUTCDate() + 1);
      nextStart.setUTCHours(0, 0, 0, 0);

      const alreadyExists = await prisma.cutoffPeriod.findFirst({
        where: {
          companyId:    settings.companyId,
          departmentId: settings.departmentId,
          periodStart:  nextStart,
        },
      });

      if (alreadyExists) {
        totalSkipped++;
        continue;
      }

      // 3. Only generate if the latest period ends within the lookahead window.
      const latestEnd = new Date(latest.periodEnd);
      latestEnd.setUTCHours(0, 0, 0, 0);

      if (latestEnd > lookaheadDate) {
        totalSkipped++;
        continue;
      }

      // 4. Carry the span from the previous period (Option A).
      const prevStart  = new Date(latest.periodStart);
      const prevEnd    = new Date(latest.periodEnd);
      const spanMs     = prevEnd.getTime() - prevStart.getTime();
      const nextEnd    = new Date(nextStart.getTime() + spanMs);
      const nextPayment = new Date(nextEnd);
      nextPayment.setUTCDate(nextPayment.getUTCDate() + settings.paymentOffsetDays);

      await prisma.cutoffPeriod.create({
        data: {
          companyId:       settings.companyId,
          departmentId:    settings.departmentId,
          periodStart:     nextStart,
          periodEnd:       nextEnd,
          paymentDate:     nextPayment,
          frequency:       settings.frequency,
          status:          "open",
          isAutoGenerated: true,
          createdBy:       adminId,
        },
      });

      totalCreated++;
      console.log(`[AUTO CUTOFF GEN] ✅ ${deptLabel}: ${nextStart.toISOString().slice(0, 10)} – ${nextEnd.toISOString().slice(0, 10)}`);
    } catch (err) {
      console.error(`[AUTO CUTOFF GEN] ❌ ${settings.department?.name ?? "No Department"}:`, err.message);
    }
  }

  console.log(`[AUTO CUTOFF GEN] Done — ${totalCreated} created, ${totalSkipped} skipped.`);
}

module.exports = autoGenerateCutoffPeriodsJob;
